CREATE TABLE IF NOT EXISTS post (
    id INTEGER PRIMARY KEY UNIQUE NOT NULL,
    content TEXT NOT NULL,
    author_id TEXT NOT NULL,
    created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS thing (
    key TEXT PRIMARY KEY UNIQUE NOT NULL,
    value TEXT
);

CREATE TABLE IF NOT EXISTS followers (
    id TEXT PRIMARY KEY UNIQUE NOT NULL,
    actor_url TEXT NOT NULL,
    object TEXT NOT NULL,
    inbox_url TEXT NOT NULL
);